version: '3'
services:
  client:
    image: def-client
    ports:
      - "80:80"
    environment:
      NODE_ENV: production
      BACKEND_URL: server:8080
  server:
    image: def-back
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://root:root@mongodb:27017/defibrillator
  mongodb:
    image: "mongo:4.2.7-bionic"
    volumes:
      - /home/ubuntu/db_data:/data/db
    ports:
      - "27017:27017"
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root