version: '3'
services:
  client:
    image: rborovets/defibrillator-client
    depends_on: 
      - server
    ports:
      - "80:80"
    environment:
      NODE_ENV: production
  server:
    image: rborovets/defibrillator-back
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb+srv://defibrillator_user:root@cluster0-hchav.mongodb.net/defibrillators_db?authSource=admin&retryWrites=true&ssl=true
  mongodb:
    image: "mongo:4.2.7-bionic"
    volumes:
      - /home/ubuntu/db_data:/data/db
    ports:
      - "27017:27017"
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root